### ISSUE TITLE
Open albums in Music.app?

### ISSUE THREAD

**Issue by jonahclarsen** [mcthomas/Apple-Music-CLI-Player#9]
Hey! First of all, awesome tool, great work.

I'm wondering if there's a way to open an album in Music.app (Apple Music or Library view), without starting to play it. I have an app that opens a bunch of albums by link but Apple frequently changes the links without adding redirects to old links, so it would be great to open an album by name.

Thank you!
Jonah

**Comment by mcthomas** [comment]
Hi Jonah- thanks!  Did you open this issue because you want this functionality added to the script?  I'm not sure it is in scope with the original goal being more of a controller, but here is an AppleScript snippet that should do what you want, with In Rainbows as an example:

```AppleScript
tell application "Music"
	activate
	set theAlbum to "In Rainbows"
	set albumTracks to (every track whose album is theAlbum)
	if (count of albumTracks) > 0 then
		set firstTrack to item 1 of albumTracks
		reveal firstTrack
	end if
end tell
```

AppleScript won't be able to query for an album outside of your Library, but this should work for any album saved to your Library (regardless of if it is downloaded).  If you want something that can query outside of your Library, you'll need to look into the [Apple Music API](https://developer.apple.com/documentation/applemusicapi).

**Comment by jonahclarsen** [comment]
Oh that's so awesome! Exactly what I wanted, thanks so much.

**Comment by jonahclarsen** [comment]
Oh that's so awesome! Exactly what I wanted, thanks so much.
